# Generated by Django 5.0.1 on 2024-01-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complete',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
